### ISSUE TITLE
ms-weapons

### ISSUE THREAD

**Issue by Zy0exe** [morais5/MS-Framework#30]
Weapons Stays Usable after being broken.

**Comment by morais5** [comment]
Hey 👋 

I will see what is going on!

Thanks for your report

**Comment by Zy0exe** [comment]
So, a good work around would be using this native:
````lua
SetCurrentPedWeapon(
	ped --[[ Ped ]], 
	weaponHash --[[ Hash ]], 
	equipNow --[[ boolean ]]
)
````
