### ISSUE TITLE
voice

### ISSUE THREAD

**Issue by filiam3** [morais5/MS-Framework#32]
o voice não esta a funcionar ouve-se todos de uma ponta a outra será que a um qb-voice ja tentei varios tipos de  mumble voip que davam no esx e procurei tambem os do qb e encontrei mas não deram

**Comment by morais5** [comment]
Boa noite, tens de ter o patreon

**Comment by Tnnuy-sv** [comment]
tenho um aqui se quiseres testar, nao sei se realmente da fix isso sem a patreon  https://cdn.discordapp.com/attachments/814298722049589290/827302476821692426/mumble-voip.rar

**Comment by filiam3** [comment]
eu tenho key patreon de 64 slots

**Comment by morais5** [comment]
> o voice não esta a funcionar ouve-se todos de uma ponta a outra será que a um qb-voice ja tentei varios tipos de mumble voip que davam no esx e procurei tambem os do qb e encontrei mas não deram

se conseguires usar esse script avisa!

**Comment by filiam3** [comment]
eu vi agora q no server.cfg não tinha o set onesync_enabled 1 meti agora
