### ISSUE TITLE
How to run it with Linux SQL?

### ISSUE THREAD

**Issue by botbull** [morais5/MS-Framework#33]
![image](https://user-images.githubusercontent.com/81786537/113370962-b753cf80-9397-11eb-9b20-823bc17647f9.png)

This is the error I get when I try to run it.

**Comment by adamsimondev** [comment]
Change the artifacts to recommended version 3539 here: https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/

**Comment by adamsimondev** [comment]
The artifacts included in the repository are made for windows, you need to replace them with the linux ones I linked.
